import { TOptionalSettings } from '../Particles/types';

export const settings: TOptionalSettings = {
  kind: 'sprite',
  instanceScale: 0.003,
  rotation: true,
  distortion: true,
  noiseType: 'curl',
  mxOctaves: 1,
  blendingMode: 'AdditiveBlending',
  instances: [
    {
      key: '1',
      visible: true,
      color: 0x333333,
      count: 30,
      density: 3500,
      radiusMin: 0.5,
      radiusMax: 0.5,
      arcMin: 0.1,
      arcMax: 0.26,
      arcRand: 1,
      speed: 0.5,
      rotationRand: 1,
      curlRand: 1,
      curlStrength: 4,
      chaosAmp: 0.4379,
      thickness: 0.1704,
      thicknessPeak: 0.5,
      pointScale: 0.0075,
    },
    {
      key: '2',
      visible: true,
      color: 0xffffff,
      count: 10,
      density: 2500,
      radiusMin: 0.5,
      radiusMax: 0.5,
      arcMin: 0.1,
      arcMax: 0.26,
      arcRand: 1,
      speed: 0.5,
      rotationRand: 1,
      curlRand: 20,
      curlStrength: 4,
      chaosAmp: 0.4379,
      thickness: 0.1704,
      thicknessPeak: 0.5,
      pointScale: 0.0075,
    },
  ],
};
